#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'livestreamer==1.12.2','console_scripts','livestreamer'
__requires__ = 'livestreamer==1.12.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
    )
