// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var Channel, Q, request;

  request = require('request');

  Q = require('q');

  Channel = (function() {
    function Channel(name, displayName) {
      this.name = name;
      this.displayName = displayName;
      this.stream = null;
    }

    Channel.prototype.onlineStatus = function() {
      var deferred;
      console.log('getting status of channel');
      deferred = Q.defer();
      request("https://api.twitch.tv/kraken/streams/" + this.name, function(error, response, body) {
        var err, stream;
        if (!error) {
          stream = {};
          try {
            stream = JSON.parse(body).stream;
            console.log('resolving stream:', stream);
            return deferred.resolve(stream);
          } catch (_error) {
            err = _error;
            console.log('Error parsing json:', err);
            stream = null;
            return deferred.reject(new Error(err));
          }
        }
      });
      return deferred.promise;
    };

    return Channel;

  })();

  module.exports = Channel;

}).call(this);
